openapi: "3.0.0"
info:
  version: 1.0.0
  title: HR App
  description: API of HR App
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost/v1
paths:
  /user:
    post:
      tags:
        - User
      operationId: createUser
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '200':
          description: User profile response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewUserResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/{userid}:
    get:
      tags:
        - User
      operationId: getUserProfile
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewUserResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /user/{userid}/changepassword/verification-code:
    put:
      tags:
        - User
      operationId: generateVerificationCode
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGenerateVerificationCode'
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        

  /user/{userid}/changepassword:
    put:
      tags:
        - User
      operationId: changeUserPassword
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestChangePassword'
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/{userid}/checkin:
    post:
      tags:
        - User
      operationId: userCheckIn
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /user/{userid}/checkout:
    post:
      tags:
        - User
      operationId: userCheckOut
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
components:
  schemas:
    NewUserResponse:
      allOf:
        - type: object
          properties:
            userId:
              type: string
            temporaryPassword:
              type: string
        - $ref: '#/components/schemas/NewUser'

    NewUser:
      type: object
      required:
        - firstName
        - lastName
        - email
        - mobileNumber
      properties:
        firstName:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,min=2,max=50
        lastName:
          type: string
        email:
          type: string
          x-oapi-codegen-extra-tags:
            validate: email
        mobileNumber:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,min=6,max=20

    RequestGenerateVerificationCode:
      type: object
      required:
        - channel
      properties:
        channel:
          type: string
          enum: [mobile, email] 

    RequestChangePassword:
      type: object
      required:
        - oldpassword
        - newpassword
        - verificationCode
      properties:
        oldpassword:
          type: string
          x-oapi-codegen-extra-tags:
              validate: required
        newpassword:
          type: string
          x-oapi-codegen-extra-tags:
              validate: required,min=8, max=30
        verificationCode:
          type: string
          x-oapi-codegen-extra-tags:
              validate: required,min=6

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string