openapi: "3.0.0"
info:
  version: 1.0.0
  title: HR App
  description: API of HR App
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost/v1
paths:
  /user:
    post:
      tags:
        - User
      operationId: createUser
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '200':
          description: User profile response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/{userid}:
    get:
      tags:
        - User
      operationId: getUserProfile
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User profile response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /user/{userid}/checkin:
    post:
      tags:
        - User
      operationId: userCheckIn
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /user/{userid}/checkout:
    post:
      tags:
        - User
      operationId: userCheckOut
      parameters:
        - name: userid
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
components:
  schemas:
    User:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
        - $ref: '#/components/schemas/NewUser'

    NewUser:
      type: object
      properties:
        firstName:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,min=2,max=50
        lastName:
          type: string
        dob:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,min=2,max=30

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string