// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/adiwenak/hrapp/ent/organisation"
	"github.com/adiwenak/hrapp/ent/schema"
	"github.com/adiwenak/hrapp/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	organisationMixin := schema.Organisation{}.Mixin()
	organisationMixinFields0 := organisationMixin[0].Fields()
	_ = organisationMixinFields0
	organisationFields := schema.Organisation{}.Fields()
	_ = organisationFields
	// organisationDescCreateTime is the schema descriptor for create_time field.
	organisationDescCreateTime := organisationMixinFields0[0].Descriptor()
	// organisation.DefaultCreateTime holds the default value on creation for the create_time field.
	organisation.DefaultCreateTime = organisationDescCreateTime.Default.(func() time.Time)
	// organisationDescUpdateTime is the schema descriptor for update_time field.
	organisationDescUpdateTime := organisationMixinFields0[1].Descriptor()
	// organisation.DefaultUpdateTime holds the default value on creation for the update_time field.
	organisation.DefaultUpdateTime = organisationDescUpdateTime.Default.(func() time.Time)
	// organisation.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	organisation.UpdateDefaultUpdateTime = organisationDescUpdateTime.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
