// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrganisationsColumns holds the columns for the "organisations" table.
	OrganisationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
	}
	// OrganisationsTable holds the schema information for the "organisations" table.
	OrganisationsTable = &schema.Table{
		Name:       "organisations",
		Columns:    OrganisationsColumns,
		PrimaryKey: []*schema.Column{OrganisationsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "mobile_number", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "need_password_reset", Type: field.TypeBool},
		{Name: "verification_code", Type: field.TypeString, Nullable: true},
		{Name: "organisation_users", Type: field.TypeInt},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_organisations_users",
				Columns:    []*schema.Column{UsersColumns[11]},
				RefColumns: []*schema.Column{OrganisationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_email_username_mobile_number",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[3], UsersColumns[4], UsersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrganisationsTable,
		UsersTable,
	}
)

func init() {
	UsersTable.ForeignKeys[0].RefTable = OrganisationsTable
}
