name: CI Backend

on:
    push:
      branches: [main]
      paths:
        - "backend/**"
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run go mod
        run: go mod download
      
      - name: Run go verify
        run: go mod verify || (echo "Go modules failed verification")
